@startuml


class Epoll{


    +Epoll(int size=100);
    +Epoll();
    +void updateChannel(Channel* ch);
    +std::vector<Channel *>  loop(int timeout=-1);
    

    -MAX_EVENTS:static const int
    -epollfd_:int
    -evs_:epoll_event [MAX_EVENTS]; 
}


@enduml